async fn lookup_message_by_body_contains<S: presage::store::Store>(
    manager: &presage::Manager<S, presage::manager::Registered>,
    thread: &presage::store::Thread,
    needle: String,
) -> Option<presage::libsignal_service::content::Content> {
    if let Ok(now) = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH) {
        //print!("(xx:xx:xx) presage: now is {now:?}.“\n");
        match manager.store().messages(thread, 0..now.as_millis() as u64).await {
            Err(_) => None,
            Ok(messages) => {
                //print!("(xx:xx:xx) presage: messages exist for this thread.\n");
                messages
                    .filter_map(|maybe_message| maybe_message.ok())
                    .filter(|content| {
                        // Iterate over &Content
                        let body = &content.body;
                        match body {
                            presage::libsignal_service::content::ContentBody::DataMessage(data_message) => data_message.body().contains(&needle),
                            presage::libsignal_service::content::ContentBody::SynchronizeMessage(sync_message) => sync_message
                                .sent
                                .as_ref()
                                .is_some_and(|sent| sent.message.as_ref().is_some_and(|data_message| data_message.body().contains(&needle))),
                            //presage::libsignal_service::content::ContentBody::EditMessage(edit_message) => … TODO
                            _ => false,
                        }
                    })
                    .nth(0) // have the first match since the store iterates over the messages backwards
            }
        }
    } else {
        None
    }
}

/*
 * In case the message text starts with "@<needle>:", returns the needle.
 *
 * Generated by ChatGPT.
 */
fn get_needle_for_replying(message_text: &str) -> Option<&str> {
    if message_text.starts_with('@') {
        if let Some(colon_pos) = message_text.find(':') {
            return Some(&message_text[1..colon_pos]);
        }
    }
    None
}

/*
 * Sends a text message to a recipient.
 *
 * Recipient may be a contact (identified by their uuid) or to a group (identified by its key).
 *
 * Optionally also sends a file.
 *
 * Taken from presage-cli
 */
pub async fn send<C: presage::store::Store + 'static>(
    manager: &mut presage::Manager<C, presage::manager::Registered>,
    recipient: crate::structs::Recipient,
    body: Option<String>,
    xfer: *const crate::bridge_structs::PurpleXfer,
    reply_to_ts: u64,
) -> Result<u64, anyhow::Error> {
    // Returns the message's sent timestamp (its serviceMessageId, in ms). The caller emits this back
    // to the transport via "webos-im-outbox-id" so a later reaction can target the user's own message.
    if let Some(body) = body.as_ref() {
        if body.len() > 2048 {
            // until https://github.com/whisperfish/presage/pull/384 is merged
            return Err(anyhow::anyhow!("Cannot send a message longer than 2048 bytes."))
        }
    }

    let timestamp = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH)?.as_millis() as u64;
    let mut data_message = presage::libsignal_service::content::DataMessage {
        timestamp: Some(timestamp),
        ..Default::default()
    };

    let body = if let Some(reply_needle) = body.as_ref().and_then(|s| get_needle_for_replying(s)) {
        let thread = match recipient {
            crate::structs::Recipient::Contact(uuid) => presage::store::Thread::Contact(presage::libsignal_service::protocol::ServiceId::Aci(uuid.into())),
            crate::structs::Recipient::ContactByPhone(_) => unreachable!("phone recipient is resolved to a UUID before send()"),
            crate::structs::Recipient::Group(key) => presage::store::Thread::Group(key),
        };
        //print!("(xx:xx:xx) presage: Trying to Quote something with {pat:?}. Thread is {thread:?}.“\n");
        if let Some(quoted_message) = lookup_message_by_body_contains(manager, &thread, reply_needle.to_string()).await {
            //print!("(xx:xx:xx) presage: Found message to quote: {quoted_message:#?}\n");
            let body = match &quoted_message.body {
                presage::libsignal_service::content::ContentBody::DataMessage(data_message) => data_message.body.clone(),
                presage::libsignal_service::content::ContentBody::SynchronizeMessage(sync_message) => {
                    sync_message.sent.as_ref().and_then(|sent| sent.message.as_ref().and_then(|data_message| data_message.body.clone()))
                }
                _ => None,
            };
            data_message.quote = Some(presage::proto::data_message::Quote {
                id: Some(quoted_message.metadata.timestamp.timestamp_millis() as u64),
                author_aci_binary: Some(quoted_message.metadata.sender.raw_uuid().as_bytes().to_vec()),
                author_aci: Some(quoted_message.metadata.sender.raw_uuid().to_string()),
                text: body,
                attachments: vec![], // TODO
                body_ranges: vec![],
                r#type: Some(0), // type: NORMAL
            });
        }
        // Note: std::string returns number of bytes (not graphemes) so we must slice instead of using chars().skip()
        Some(body.as_ref().unwrap()[(reply_needle.len() + 2)..].to_string())
    } else {
        body
    };

    // webOS replies: if the app supplied a reply target (the quoted message's sent timestamp), look
    // that message up in the store and attach a Signal Quote so the reply threads on other clients.
    // This is the structured counterpart to the "@needle:" stopgap above; when both are present this
    // (explicit target) wins. 0 == not a reply.
    if reply_to_ts != 0 {
        let thread = match recipient {
            crate::structs::Recipient::Contact(uuid) => presage::store::Thread::Contact(presage::libsignal_service::protocol::ServiceId::Aci(uuid.into())),
            crate::structs::Recipient::ContactByPhone(_) => unreachable!("phone recipient is resolved to a UUID before send()"),
            crate::structs::Recipient::Group(key) => presage::store::Thread::Group(key),
        };
        if let Ok(Some(quoted_message)) = manager.store().message(&thread, reply_to_ts).await {
            let quoted_body = match &quoted_message.body {
                presage::libsignal_service::content::ContentBody::DataMessage(dm) => dm.body.clone(),
                presage::libsignal_service::content::ContentBody::SynchronizeMessage(sm) => {
                    sm.sent.as_ref().and_then(|sent| sent.message.as_ref().and_then(|dm| dm.body.clone()))
                }
                _ => None,
            };
            let author = quoted_message.metadata.sender.raw_uuid();
            data_message.quote = Some(presage::proto::data_message::Quote {
                id: Some(reply_to_ts),
                author_aci_binary: Some(author.as_bytes().to_vec()),
                author_aci: Some(author.to_string()),
                text: quoted_body,
                attachments: vec![], // TODO
                body_ranges: vec![],
                r#type: Some(0), // type: NORMAL
            });
        }
    }

    if xfer != std::ptr::null_mut() {
        let path = crate::bridge::xfer_get_local_filename(xfer);
        let blob = std::fs::read(path.clone())?;
        let content_type = mime_sniffer::MimeTypeSniffer::sniff_mime_type(&blob).unwrap_or("*/*"); // NOTE: I saw this being used in Signal over application/octet-stream
        let attachment = make_attachment(blob.clone(), content_type.to_string(), std::path::PathBuf::from(path));
        let upload_attachments_result = manager.upload_attachments(vec![attachment]).await?;
        let pointer = upload_attachments_result.into_iter().next().ok_or(anyhow::anyhow!("Not a single attachment upload succeeded."))??;
        data_message.attachments.push(pointer.clone());
    }

    data_message.body = body;
    match recipient {
        crate::structs::Recipient::Contact(uuid) => {
            manager
                .send_message(
                    presage::libsignal_service::protocol::ServiceId::Aci(uuid.into()),
                    presage::libsignal_service::content::ContentBody::DataMessage(data_message),
                    timestamp,
                )
                .await?;
        }
        crate::structs::Recipient::ContactByPhone(_) => unreachable!("phone recipient is resolved to a UUID before send()"),
        crate::structs::Recipient::Group(master_key) => {
            data_message.group_v2 = Some(presage::proto::GroupContextV2 {
                master_key: Some(master_key.to_vec()),
                revision: Some(0),
                ..Default::default()
            });
            manager
                .send_message_to_group(&master_key, presage::libsignal_service::content::ContentBody::DataMessage(data_message), timestamp)
                .await?;
        }
    }

    Ok(timestamp)
}

/*
 * Looks up the ACI (author) of a stored message by its sent timestamp within a thread.
 *
 * Used to fill Reaction.target_author_aci, which the reaction signal does not carry. For an incoming
 * message the sender is the peer; for our own (synchronized) message it is our own ACI -- so this
 * resolves both directions correctly, provided the message is in the store.
 */
async fn lookup_message_author_by_timestamp<S: presage::store::Store>(
    manager: &presage::Manager<S, presage::manager::Registered>,
    thread: &presage::store::Thread,
    timestamp: u64,
) -> Option<presage::libsignal_service::prelude::Uuid> {
    match manager.store().message(thread, timestamp).await {
        Ok(Some(content)) => Some(content.metadata.sender.raw_uuid()),
        _ => None,
    }
}

/*
 * Sends a reaction (an ordinary outgoing DataMessage with the `reaction` field set) to a recipient.
 *
 * `target_ts` is the reacted-to message's sent timestamp; `emoji` is always supplied (even on removal
 * so backends that retract a specific reaction have it); `remove` true retracts the user's reaction.
 */
pub async fn send_reaction<C: presage::store::Store + 'static>(
    manager: &mut presage::Manager<C, presage::manager::Registered>,
    recipient: crate::structs::Recipient,
    target_ts: u64,
    emoji: String,
    remove: bool,
) -> Result<(), anyhow::Error> {
    // Build the thread that keys the store lookup for the reacted-to message's author.
    let thread = match &recipient {
        crate::structs::Recipient::Contact(uuid) => {
            presage::store::Thread::Contact(presage::libsignal_service::protocol::ServiceId::Aci((*uuid).into()))
        }
        crate::structs::Recipient::ContactByPhone(_) => unreachable!("phone recipient is resolved to a UUID before send_reaction()"),
        crate::structs::Recipient::Group(key) => presage::store::Thread::Group(*key),
    };

    // Resolve the target author's ACI. The store lookup is authoritative for both incoming and own
    // (synchronized) messages. Groups MUST use it (Signal requires the correct author). For a 1:1 we
    // fall back to the peer UUID if the message is not in the store (the common case: reacting to a
    // message the peer sent us); reacting to our OWN 1:1 message that is not in the store is the only
    // case this mis-attributes -- see the runtime note.
    let target_author = match lookup_message_author_by_timestamp(manager, &thread, target_ts).await {
        Some(uuid) => uuid,
        None => match &recipient {
            crate::structs::Recipient::Contact(uuid) => *uuid,
            _ => {
                return Err(anyhow::anyhow!(
                    "Cannot resolve reaction target author for timestamp {target_ts} (message not in store)."
                ))
            }
        },
    };

    let timestamp = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH)?.as_millis() as u64;
    let reaction = presage::proto::data_message::Reaction {
        emoji: Some(emoji),
        remove: Some(remove),
        target_author_aci: Some(target_author.to_string()),
        target_sent_timestamp: Some(target_ts),
        target_author_aci_binary: Some(target_author.as_bytes().to_vec()),
    };
    let mut data_message = presage::libsignal_service::content::DataMessage {
        timestamp: Some(timestamp),
        reaction: Some(reaction),
        ..Default::default()
    };

    match recipient {
        crate::structs::Recipient::Contact(uuid) => {
            manager
                .send_message(
                    presage::libsignal_service::protocol::ServiceId::Aci(uuid.into()),
                    presage::libsignal_service::content::ContentBody::DataMessage(data_message),
                    timestamp,
                )
                .await?;
        }
        crate::structs::Recipient::ContactByPhone(_) => unreachable!("phone recipient is resolved to a UUID before send_reaction()"),
        crate::structs::Recipient::Group(master_key) => {
            data_message.group_v2 = Some(presage::proto::GroupContextV2 {
                master_key: Some(master_key.to_vec()),
                revision: Some(0),
                ..Default::default()
            });
            manager
                .send_message_to_group(&master_key, presage::libsignal_service::content::ContentBody::DataMessage(data_message), timestamp)
                .await?;
        }
    }

    Ok(())
}

/*
 * Constructs the AttachmentSpec out of bytes
 *
 * Taken from flare, mostly
 */
pub fn make_attachment(
    bytes: Vec<u8>,
    content_type: String,
    path: std::path::PathBuf,
) -> (presage::libsignal_service::sender::AttachmentSpec, Vec<u8>) {
    (
        presage::libsignal_service::sender::AttachmentSpec {
            content_type: content_type,
            length: bytes.len(),
            file_name: path.file_name().map(|f| f.to_string_lossy().to_string()),
            preview: None,
            voice_note: None,
            borderless: None,
            width: None,  // TODO: find out if this is needed for images
            height: None, // TODO: find out if this is needed for images
            caption: None,
            blur_hash: None, // TODO: find out if this is needed for images
        },
        bytes,
    )
}
