#!/bin/bash
# Verify the plugin call services compile against BOTH webOS luna-service2 versions.
#
# Legacy webOS 3.0.5 has a split public/private bus; luna-service2 3.x (LuneOS) has a single bus
# and removed the whole LSPalmService API -- LSRegisterPalmService, LSPalmServiceRegisterCategory,
# LSGmainAttachPalmService and both connection accessors, plus the type itself. All four call
# services in this tree used that API directly, so none of them could build for LuneOS.
#
# common/webos-ls2-compat.h re-expresses the legacy API on the modern one; this script is what
# keeps that true. It compiles each call implementation against both header sets.
#
# Compile-only. Linking the plugins needs the full device staging (and, for Teams, gstreamer-0.10
# libraries that only exist in a rootfs image), none of which bears on the API question here.
set -u

MSG=$(cd "$(dirname "$0")" && pwd)
DEPS=${DEPS:-/home/herrie/webos/touchpad-kernel/doctor305/build-deps}
LUNEOS=${LUNEOS:-/media/herrie/LuneOS/scarthgap/webos-ports}
LUNE=$LUNEOS/tmp-glibc/sysroots-components/corei7-64
PURPLE=${PURPLE:-$MSG/libpurple}
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

LEGACY_LS2="-I$DEPS/luna-service2/include/public
            -I$DEPS/luna-service2/include/public/luna-service2
            -I$DEPS/woce-build-support/staging/arm-none-linux-gnueabi/include/PmLogLib/IncsPublic"
MODERN_LS2="-I$LUNE/luna-service2/usr/include
            -I$LUNE/luna-service2/usr/include/luna-service2
            -I$LUNE/libpbnjson/usr/include
            -I$LUNE/pmloglib/usr/include"

[ -d "$DEPS/luna-service2/include/public" ] || { echo "!! legacy luna-service2 headers not at $DEPS"; exit 1; }
[ -d "$LUNE/luna-service2" ] || { echo "!! LuneOS sysroot not at $LUNE (set LUNEOS=)"; exit 1; }

# Everything is compiled with the ARM cross-compiler against the device staging, and ONLY the
# luna-service2 headers are swapped between the two passes. That isolates the variable under
# test. It also avoids two dead ends: libwhatsmeow.h is generated by the 32-bit ARM cgo build and
# static-asserts 32-bit pointers, so it cannot be compiled on a 64-bit host at all, and glib's
# glibconfig.h is arch-specific. luna-service2's own headers are arch-independent, so pointing an
# ARM compile at the LuneOS header set is a valid test of the API surface.
TC=${TC:-/home/herrie/x-tools/arm-unknown-linux-gnueabi-gcc125/bin/arm-unknown-linux-gnueabi-}
GLIB_STAGING=${GLIB_STAGING:-/home/herrie/webos/wpe/staging-glibc-252}
PURPLE_INC="-I$PURPLE/include/libpurple -I$PURPLE/include"
GLIB="-I$GLIB_STAGING/include -I$GLIB_STAGING/include/glib-2.0 -I$GLIB_STAGING/lib/glib-2.0/include"

command -v "${TC}gcc" >/dev/null || { echo "!! ARM toolchain not at $TC (set TC=)"; exit 1; }

# whatsapp needs libwhatsmeow.h, which cgo generates into the plugin's build dir, and teams
# needs json-glib from the device staging -- neither is on a default include path, and neither
# has anything to do with luna-service2.
WAGEN=$MSG/facebook-e2ee/plugin/purple-combined/build-arm
JSONGLIB=${JSONGLIB:-/home/herrie/webos/wpe/staging-glibc-252/include/json-glib-1.0}

PLUGINS="
telegram:$MSG/telegram/plugin/tdlib-purple/call-luna.cpp:-I$MSG/telegram/plugin/tdlib-purple
signal:$MSG/signal/plugin/purple-presage/src/c/call.c:-I$MSG/signal/plugin/purple-presage/src/c
whatsapp:$MSG/facebook-e2ee/plugin/purple-combined/glue/call.c:-I$MSG/facebook-e2ee/plugin/purple-combined/glue -I$WAGEN -I$MSG/facebook-e2ee/plugin/purple-combined
teams:$MSG/teams/plugin/purple-teams/teams_call_luna.c:-I$MSG/teams/plugin/purple-teams -I$MSG/teams/plugin/purple-teams/purple2compat -I$JSONGLIB
"

RC=0
check() {  # check <stack-label> <ls2 includes> <purple includes>
  local label=$1 ls2=$2 purple=$3
  echo "$label"
  echo "$PLUGINS" | while IFS= read -r entry; do
    [ -z "$entry" ] && continue
    local name src extra cc
    name=${entry%%:*}; entry=${entry#*:}
    src=${entry%%:*}; extra=${entry#*:}
    [ -f "$src" ] || { printf "  %-10s SKIP (no %s)\n" "$name" "$src"; continue; }
    case "$src" in *.cpp) cc="${TC}g++ -std=c++17";; *) cc="${TC}gcc -std=gnu11";; esac
    # shellcheck disable=SC2086
    if $cc -fsyntax-only -fPIC -DPURPLE_PLUGINS -DPLUGIN_VERSION='"dual-target-check"' \
         -I"$MSG/common" $ls2 $purple $GLIB $extra "$src" > "$TMP/$name-$label.log" 2>&1; then
      printf "  %-10s ok\n" "$name"
    else
      printf "  %-10s FAILED\n" "$name"
      grep -m3 "error:" "$TMP/$name-$label.log" | sed 's/^/      /'
      echo FAIL >> "$TMP/rc"
    fi
  done
}

check "legacy luna-service2 (split bus, webOS 3.0.5)" "$LEGACY_LS2" "$PURPLE_INC"
check "modern luna-service2 3.21.2 (single bus, LuneOS)" "$MODERN_LS2" "$PURPLE_INC"

echo
if [ -e "$TMP/rc" ]; then echo "!! plugins do not build for both targets"; RC=1
else echo "all call services compile for both targets"; fi
exit $RC
