set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER   /home/herrie/x-tools/arm-unknown-linux-gnueabi-gcc125/bin/arm-unknown-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER /home/herrie/x-tools/arm-unknown-linux-gnueabi-gcc125/bin/arm-unknown-linux-gnueabi-g++)
set(CMAKE_SYSROOT /home/herrie/x-tools/arm-unknown-linux-gnueabi-gcc125/arm-unknown-linux-gnueabi/sysroot)
set(CMAKE_FIND_ROOT_PATH "/home/herrie/x-tools/arm-unknown-linux-gnueabi-gcc125/arm-unknown-linux-gnueabi/sysroot;/home/herrie/webos/wpe/staging-glibc-252")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(_arch "-march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp")
set(CMAKE_C_FLAGS   "${_arch}" CACHE STRING "")
set(CMAKE_CXX_FLAGS "${_arch}" CACHE STRING "")
# help find_package(OpenSSL/ZLIB) land in the staging sysroot
set(OPENSSL_ROOT_DIR /home/herrie/webos/wpe/staging-glibc-252)
set(OPENSSL_INCLUDE_DIR /home/herrie/webos/wpe/staging-glibc-252/include)
set(OPENSSL_CRYPTO_LIBRARY /home/herrie/webos/wpe/staging-glibc-252/lib/libcrypto.so)
set(OPENSSL_SSL_LIBRARY /home/herrie/webos/wpe/staging-glibc-252/lib/libssl.so)
set(ZLIB_ROOT /home/herrie/webos/wpe/staging-glibc-252)
set(ZLIB_INCLUDE_DIR /home/herrie/webos/wpe/staging-glibc-252/include)
set(ZLIB_LIBRARY /home/herrie/webos/wpe/staging-glibc-252/lib/libz.so)
